name: Update master
on:
  push:
    branches:
      - workflows
  schedule:
    # every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: true
jobs:
  update-nixos:
    name: Update master
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: thoughtfull-systems/checkout@main
        with:
          ref: master
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Add upstream remote
        shell: bash
        run: git remote add -t master --no-tags -f upstream "https://github.com/nix-community/home-manager.git"
      - name: Merge from upstream/master
        shell: bash
        run: git merge --no-ff upstream/master
      - name: Merge branches
        shell: bash
        run: |
          git merge --no-ff origin/workflows
      - name: Push to origin
        shell: bash
        run: git push origin master
